// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQWuKV6n_gB7mTm0FOo8ySHStN9878LE',
    appId: '1:806289354637:web:a181931deb3a4845c657c4',
    messagingSenderId: '806289354637',
    projectId: 'cybersecurityapp-ff08a',
    authDomain: 'cybersecurityapp-ff08a.firebaseapp.com',
    storageBucket: 'cybersecurityapp-ff08a.firebasestorage.app',
    measurementId: 'G-5BWHGCY2EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiy5bth5AVMk1DwBxjjFZxslSkGrDAv0',
    appId: '1:806289354637:android:03215f9e20b54d68c657c4',
    messagingSenderId: '806289354637',
    projectId: 'cybersecurityapp-ff08a',
    storageBucket: 'cybersecurityapp-ff08a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0EZJkuQzL-OBDG66dg2AfvFHn5HbdLKU',
    appId: '1:806289354637:ios:662f3bb47c084effc657c4',
    messagingSenderId: '806289354637',
    projectId: 'cybersecurityapp-ff08a',
    storageBucket: 'cybersecurityapp-ff08a.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0EZJkuQzL-OBDG66dg2AfvFHn5HbdLKU',
    appId: '1:806289354637:ios:662f3bb47c084effc657c4',
    messagingSenderId: '806289354637',
    projectId: 'cybersecurityapp-ff08a',
    storageBucket: 'cybersecurityapp-ff08a.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQWuKV6n_gB7mTm0FOo8ySHStN9878LE',
    appId: '1:806289354637:web:479e7d2fcd595767c657c4',
    messagingSenderId: '806289354637',
    projectId: 'cybersecurityapp-ff08a',
    authDomain: 'cybersecurityapp-ff08a.firebaseapp.com',
    storageBucket: 'cybersecurityapp-ff08a.firebasestorage.app',
    measurementId: 'G-FRYS9YPGNJ',
  );
}
